### ISSUE TITLE
Message of the day: Allow teachers to specify a message of the day

### ISSUE THREAD

**Issue by IvonArroyo** [center-for-knowledge-communication/mathspring#150]
It would be great for teeachers to specify a message of the day from the Teacher Tools.
 
This would Allow teachers to specify a message of the day, that pops up the next time a student in the class logs in.  This would allow the teacher to tell students to focus on specific aspects, such as going to the progress page and working on topics that have plants withering or not blooming yet.

**Comment by IvonArroyo** [comment]
This one is increasing in priority...

**Comment by wlee-umass** [comment]
- Created a new class called WillTestMessageClass
- Generated 4 test students
- Created a test message of the day. Couldn't figure out how to enter the "Choose date range." Nothing happened when I clicked on the button. Submitted my test message anyway
- Logged in as student 1765tester1
- Saw the "Today messages" box but not my message

![image](https://user-images.githubusercontent.com/58573767/132743947-cd753b1b-e82c-4016-9527-c8c4b6cc2f1c.png)

![image](https://user-images.githubusercontent.com/58573767/132743968-cee846d9-c352-46d3-aace-7fe9c3562a07.png)

**Comment by FrankSylvia** [comment]
Thanks, Will.

I see that I missed 2 .js files when I checked in this feature.

I'm going to send a fix right away.

Frank

**Comment by FrankSylvia** [comment]
Hi Will,

I also found that I had not created a db table 'classmessages' for this
feature. I have corrected this and tested the feature. Please give it a try
now.

Thanks,
Frank

**Comment by wlee-umass** [comment]
Date Range calendar worked! and was able to submit a message for my test class WillTestMessageClass:

![image](https://user-images.githubusercontent.com/58573767/132993073-9bd867ec-286f-428b-80a6-75ea43c28f81.png)

However, the message of the day is still not showing up. I tried three different test students (1765tester1, 1765tester2, wtmc-176504) of the test class. All three of them saw an empty message box:

![image](https://user-images.githubusercontent.com/58573767/132993156-e2c6c3c3-9411-4683-83d5-f65c1a698981.png)

Is there something else I got to do to turn the message "on?"

**Comment by FrankSylvia** [comment]
Try clearing your browser cache.

**Comment by wlee-umass** [comment]
Hmmm, you going to hate me. Cleared the cache.

But I still can't see the message in the message box. I created a brand new class and 5 new students to test. I could specify the date range, message, and submitted it. Maybe I could show you what and how I did it in our Softwareengineering meeting.
