### ISSUE TITLE
there are times that you can have multiple audio sources playing at once,

### ISSUE THREAD

**Issue by FrankSylvia** [center-for-knowledge-communication/mathspring#317]
-Tutor sometimes speaks over problems
-When the problem is playing, clicking on a hint plays the hint audio at
the same time
-There have been a few cases where I can get multiple hint audios to
play at the same time
-When a hint is playing, clicking on the problem stops the hint and
starts the problem audio: This is ideal, can the others also do
something similar?

**Comment by WillRebel** [comment]
Another issue I found:
Finishing a problem with a correct answer while a hint is being read leads to the tutor talking to you (congratulations, your hard work paid off) while the hint is still being read.

**Comment by FrankSylvia** [comment]
Fixed:  -There have been a few cases where I can get multiple hint audios to
play at the same time

**Comment by FrankSylvia** [comment]
The rest of these are complicated by having multiple IFrames using the audio simulatneously.  It was agreed that we would postponed further changes at this time.

**Comment by FrankSylvia** [comment]
Kartik, could you please take a try at this one?

**Comment by FrankSylvia** [comment]
Fixed collisions between Read Problem and Read Hint, also also mutliple Hints using audio at the same time.

Have not fixed collisions between Problem audios and Companion audios.  Will create a new issue for that.

**Comment by WillRebel** [comment]
I have tested the fixes Frank noted, they work as expected. (No collisions between problem audio sources, collisions still exist problem vs companion)

I had to answer the same survey twice in order to start using mathspring, and got a score of 0/1 both times (16 question survey). It also looks like Jake has been disabled, is that all expected behavior or should I make a new issue?

**Comment by FrankSylvia** [comment]
This issue addresses collisions between audio requests made by user interaction with the Problem Screen. 

It does not address collision between the Learning Companion and the user's interactions.
